version: '3.8'

services:
  backend:
    build: ./backend
    container_name: p2p-backend
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - p2p-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: p2p-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - p2p-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: p2p-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - p2p-network
    restart: unless-stopped

volumes:
  backend_uploads:
    driver: local

networks:
  p2p-network:
    driver: bridge